language: java

# we test at Ubuntu Trusty (Ubuntu 14.04 LTS)
# see https://docs.travis-ci.com/user/trusty-ci-environment/
# This environment is continuously updated as described in https://docs.travis-ci.com/user/build-environment-updates/
dist: trusty
sudo: required

git:
  depth: 1

services:
  - postgresql
  - mysql
  - docker

env:
  global:
    - GRADLE_OPTS=-Dorg.gradle.daemon=false
    - TERM=dumb
  matrix:
    - TEST_SUITE=check OPTIONS=modernizer
    - TEST_SUITE=checkstyle
    - TEST_SUITE=fetcherTest
    - TEST_SUITE=databaseTest
    - TEST_SUITE=guiTest
    - TEST_SUITE=codecov
    - TEST_SUITE=snapcraft
    - DEPENDENCY_UPDATES=check

matrix:
    fast_finish: true
    allow_failures:
      - env: TEST_SUITE=fetcherTest
      - env: TEST_SUITE=codecov
      - env: DEPENDENCY_UPDATES=check

# JavaFX localization tests need a running X environment
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: true

before_script:
  - psql -c 'create database jabref;' -U postgres
  - mysql -u root -e 'create database jabref'

script:
  # --scan enables the Gradle build scan, which can be used to investigate the time each action consumes
  # For more information see https://gradle.com/scans/get-started
  - if [ "$TEST_SUITE" != "checkstyle" ] && [ "$TEST_SUITE" != "guiTest" ] && [ "$TEST_SUITE" != "codecov" ]  && [ "$TEST_SUITE" != "snapcraft" ]; then ./gradlew $TEST_SUITE $OPTIONS --scan; fi
  - if [ "$TEST_SUITE" == "checkstyle" ]; then ./gradlew checkstyleMain checkstyleTest checkstyleJmh; fi
  - if [ "$TEST_SUITE" == "guiTest" ]; then ./buildres/gui-tests.sh; fi
  - if [ "$TEST_SUITE" == "codecov" ]; then ./gradlew jacocoTestReport; bash <(curl -s https://codecov.io/bash); fi
  - if [ "$TRAVIS_BRANCH" == "snapcraft-travis" ] && [ "$TEST_SUITE" == "snapcraft" ]; then openssl aes-256-cbc -K $encrypted_5f91cda8b19d_key -iv $encrypted_5f91cda8b19d_iv -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d && sh ./scripts/run-snapcraft.sh; fi
  - if [ "$DEPENDENCY_UPDATES" == "check" ]; then ./gradlew -q checkOutdatedDependencies; fi

after_failure:
  # show test results if build fails
  - $TRAVIS_BUILD_DIR/scripts/after-failure.sh

branches:
  only:
    - master
    - maintable-beta
    - snapcraft-travis

# cache gradle dependencies
# https://docs.travis-ci.com/user/languages/java#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
